"""campaign locks

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-18 17:01:31.765949
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_locks',
    sa.Column('campaign_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    with op.batch_alter_table('campaign_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_locks_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_locks_expires_at'))

    op.drop_table('campaign_locks')
    # ### end Alembic commands ###
