"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 14:29:54.809726
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keitaro_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('geo', sa.JSON(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('traffic_source_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('streams_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_keitaro_id'), ['keitaro_id'], unique=True)

    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('offers',
    sa.Column('keitaro_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('affiliate_network_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.JSON(), nullable=False),
    sa.Column('offer_type', sa.String(length=32), nullable=False),
    sa.Column('payout_value', sa.String(length=32), nullable=False),
    sa.Column('payout_currency', sa.String(length=8), nullable=False),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('keitaro_id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('keitaro_campaign_id', sa.Integer(), nullable=True),
    sa.Column('keitaro_stream_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_keitaro_campaign_id'), ['keitaro_campaign_id'], unique=False)

    op.create_table('streams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('keitaro_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('schema', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streams_keitaro_id'), ['keitaro_id'], unique=True)

    op.create_table('stream_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('share', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('kt_state', sa.String(length=16), nullable=True),
    sa.Column('kt_share', sa.Integer(), nullable=True),
    sa.Column('kt_binding_id', sa.Integer(), nullable=True),
    sa.Column('was_published', sa.Boolean(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id', 'offer_id', name='uq_stream_offer')
    )
    with op.batch_alter_table('stream_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_offers_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index('ix_stream_offers_stream_state', ['stream_id', 'state'], unique=False)

    op.create_table('stream_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('offers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stream_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_snapshots_stream_id'), ['stream_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_snapshots_stream_id'))

    op.drop_table('stream_snapshots')
    with op.batch_alter_table('stream_offers', schema=None) as batch_op:
        batch_op.drop_index('ix_stream_offers_stream_state')
        batch_op.drop_index(batch_op.f('ix_stream_offers_offer_id'))

    op.drop_table('stream_offers')
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streams_keitaro_id'))

    op.drop_table('streams')
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_keitaro_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_operations_created_at'))
        batch_op.drop_index(batch_op.f('ix_operations_action'))

    op.drop_table('operations')
    op.drop_table('offers')
    op.drop_table('idempotency_records')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_keitaro_id'))

    op.drop_table('campaigns')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
